import {
	APIMessage,
	APIReaction,
	InteractionType,
	MessageActivityType,
	MessageFlags,
	MessageType,
	Snowflake,
} from 'discord-api-types';
import { Client } from '../../clients';
import { Guild } from '../guild/Guild';
/*import { GuildChannel } from '../channel/GuildChannel';
import { GuildMember } from '../guild/GuildMember';*/
import { User } from '../User';
import { Application } from '../Application';
import { Embed } from './MessageEmbed';
import { Sticker } from './Sticker';
import { MessageAttachment } from './MessageAttachment';

interface MessageActivity {
	/**
	 * The type of message activity
	 */
	type: MessageActivityType;

	/**
	 * The id of a party from a Rich Presence event
	 */
	partyId?: string;
}

interface MessageReference {
	/**
	 * The id of the originating message
	 */
	messageId?: Snowflake;

	/**
	 * The id of the originating message's channel
	 */
	channelId: Snowflake;

	/**
	 * The id of the originating message's guild
	 */
	guildId?: Snowflake;
}

interface MessageInteraction {
	/**
	 * The id of the interaction
	 */
	id: Snowflake;

	/**
	 * The type of interaction
	 */
	type: InteractionType;

	/**
	 * The name of the application command
	 */
	name: string;

	/**
	 * The user who invoked the interaction
	 */
	user: User;
}

/**
 * Structure representing a message
 */
export class Message {
	/**
	 * The id of the message
	 */
	public id!: Snowflake;

	/**
	 * The id of the channel the message was sent in
	 */
	public channelId!: Snowflake;

	/**
	 * The id of the guild the message was sent in
	 */
	public guildId?: Snowflake;

	/**
	 * The author of the message
	 */
	public author!: User;

	/**
	 * The content of the message
	 */
	public content!: string;

	/**
	 * The timestamp when the message was created
	 */
	public createdTimestamp!: number;

	/**
	 * The date when the message was created
	 */
	public createdAt!: Date;

	/**
	 * The timestamp when the message was edited
	 */
	public editedTimestamp?: number;

	/**
	 * The date when the message was edited
	 */
	public editedAt?: Date;

	/**
	 * Whether the message was a TTS message
	 */
	public tts!: boolean;

	/* public mentionEveryone!: boolean;
	public mentions!: (User & {
		member?: Omit<GuildMember, 'user'>;
	})[];
	public mentionRoles!: Snowflake[];
	public mentionChannels?: APIChannelMention[];*/

	/**
	 * The attached files of the message
	 */
	public attachments!: MessageAttachment[];

	/**
	 * The embeds of the message
	 */
	public embeds!: Embed[];

	/**
	 * The reactions of the message
	 */
	public reactions?: APIReaction[];

	/**
	 * Used for validating a message was sent
	 */
	public nonce?: string | number;

	/**
	 * Whether the message is pinned
	 */
	public pinned!: boolean;

	/**
	 * The webhook's id of the message if generated by one
	 */
	public webhookId?: Snowflake;

	/**
	 * The type of message
	 */
	public type!: MessageType;

	/**
	 * Sent with Rich Presence-related chat embeds
	 */
	public activity?: MessageActivity;

	/**
	 * Sent with Rich Presence-related chat embeds
	 */
	public application?: Partial<Application>;

	/**
	 * Data showing the source of a crosspost, channel follow add, pin, or reply message
	 */
	public messageReference?: MessageReference;

	/**
	 * The flags of the message
	 */
	public flags?: MessageFlags;

	/**
	 * The stickers sent with the message
	 */
	public stickers?: Sticker[];

	/**
	 * the message associated with the messageReference property
	 */
	public referencedMessage?: Message;

	/**
	 * Sent if the message is a response to an Interaction
	 */
	public interaction?: MessageInteraction;

	/**
	 * The guild the message was sent in
	 */
	public guild!: Guild;

	/**
	 * The URL of the message
	 */
	public url!: string;

	public constructor(public readonly client: Client, data: APIMessage) {
		this.$patch(data);
	}

	public $patch(data: APIMessage): void {
		this.id = data.id;
		this.channelId = data.channel_id;
		this.guildId = data.guild_id;
		this.author = new User(this.client, data.author);
		this.content = data.content;
		this.createdTimestamp = Number(data.timestamp);
		this.createdAt = new Date(data.timestamp);
		this.editedTimestamp = Number(data.edited_timestamp);
		this.editedAt = this.editedTimestamp ? new Date(this.editedTimestamp) : undefined;
		this.tts = data.tts;
		/*this.mentionEveryone = data.mention_everyone;
		this.mentions = data.mentions;
		this.mentionRoles = data.mention_roles;
		this.mentionChannels = data.mention_channels;*/
		this.attachments = data.attachments.map((attachment) => new MessageAttachment(attachment));
		this.embeds = data.embeds.map((embed) => new Embed(embed));
		this.reactions = data.reactions;
		this.nonce = data.nonce;
		this.pinned = data.pinned;
		this.webhookId = data.webhook_id;
		this.type = data.type;
		this.activity = data.activity && {
			type: data.activity.type,
			partyId: data.activity.party_id,
		};
		this.application = data.application && new Application(this.client, data.application);
		this.messageReference = data.message_reference && {
			messageId: data.message_reference.message_id,
			channelId: data.message_reference.channel_id,
			guildId: data.message_reference.guild_id,
		};
		this.flags = data.flags;
		this.stickers = data.stickers?.map((sticker) => new Sticker(this.client, sticker));
		// this.referencedMessage = data.referenced_message ? new Message(this.channel, data.referenced_message) : undefined;
		this.interaction = data.interaction && {
			...data.interaction,
			user: new User(this.client, data.interaction.user),
		};
		this.url = `https://discord.com/channels/${this.guildId || '@me'}/${this.channelId}/${this.id}`;
	}

	/*public get member(): GuildMember | undefined {
		return this.guild ? this.guild.members.get(this.author.id) : undefined;
	}*/

	public toString(): string {
		return this.content;
	}
}
